[package]
name = "rust-practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[workspace]
members = [
    "session1/vars",
    "guessing_game",
    "local-cache",
    "session1/auth"
    , "session1/login"]
